input_folder = "archive"
metadata_file = "symbols_valid_meta.csv"
etfs_folder = "etfs"
stocks_folder = "stocks"
semi_processed_data_folder = "semi-processed"
semi_processed_file_name = "semi-processed_data.parquet"
processed_data_folder = "processed"
processed_file_name = "processed_data.parquet"